version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Utiliza el Dockerfile de desarrollo
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

networks:
  mynetwork:
    driver: bridge