version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod  # Utiliza el Dockerfile de producción
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      - FLASK_ENV=production
      - ODOO_URL=${ODOO_URL}
      - ODOO_DB=${ODOO_DB}
      - ODOO_USERNAME=${ODOO_USERNAME}
      - ODOO_API_KEY=${ODOO_API_KEY}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - ODOO_RPC_TIMEOUT=${ODOO_RPC_TIMEOUT}
      - FIREBASE_JSON_NAME=${FIREBASE_JSON_NAME}
      - FIREBASE_COLLECTION_PREFIX=${FIREBASE_COLLECTION_PREFIX}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
networks:
  mynetwork:
    driver: bridge