FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . .

# Copiar .env.example a .env
#RUN cp .env.example .env

# Instalar dependencias de producción
RUN pip install -r requirements.txt
RUN pip install -r requirements-prod.txt

# Exponer el puerto en el que correrá la aplicación
EXPOSE 5000

# Establecer variables de entorno para producción
ENV FLASK_DEBUG=false
ENV FLASK_RUN_PORT=5000

# Comando para ejecutar la aplicación usando Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--timeout", "120","app:app"]
