version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod  # Utiliza el Dockerfile de producción
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
